<a href="https://colab.research.google.com/github/DANeS-Lab/practise/blob/master/NumpyTensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import tensorflow as tf

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
l=[ [1,2], [3, "a"]]
m=np.array(l)
print (m, type(m), m.shape)

[['1' '2']
 ['3' 'a']] <class 'numpy.ndarray'> (2, 2)


# **Dimensions**

In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

0
1
2
3
[[[[[1 2 3 4]]]]]
number of dimensions : 5


# **Access Elements of Array**

In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd dim: ', arr[1, 4])
print('Last element from 2nd dim: ', arr[1, -1])

5th element on 2nd dim:  10
Last element from 2nd dim:  10


# **Datatype**

In [6]:
arr = np.array([1, 2.76, 3, 4.8], dtype='f4')
print(arr)
print(arr.dtype) 
print (arr.astype(int))

[1.   2.76 3.   4.8 ]
float32
[1 2 3 4]


In [7]:
arr = np.array([1, 0, 3, -5])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype) 

[ True False  True  True]
bool


# **Slicing**

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[0:6:2])
print(arr[-3:-1]) 
print (arr[::2])

[1 3 5]
[8 9]
[1 3 5 7 9]


# **Copy View**

In [9]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [10]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base) 

None
[1 2 3 4 5]


# **Reshape**

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print (arr.reshape(2, 4))
print(arr.reshape(2, 4).base)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


# **Iterate**

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

#row wise
for x in arr:
  print(x)
  
#each element

for tup, v in np.ndenumerate(arr):
  print (tup, v)

for x in np.nditer(arr):
  print(x)

[1 2 3]
[4 5 6]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
1
2
3
4
5
6


In [13]:
#arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [76]:
arr=np.array([1, 2, 3, 4, 5])
squaring=lambda t: t**2
vfunc=np.vectorize(squaring)
vfunc(arr)

array([ 1,  4,  9, 16, 25])

# **Join**

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))#default axis=0
print(arr)

[1 2 3 4 5 6]


In [77]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0) ##creating each element of new array by axis
print(arr, arr.shape)
arr = np.concatenate((arr1, arr2), axis=1) ##creating each element of new array by axis
print(arr, arr.shape) 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)
[[1 2 5 6]
 [3 4 7 8]] (2, 4)


In [82]:
#stacking

#arr1 = np.array([1, 2, 3])
#arr2 = np.array([4, 5, 6])
arr1 = np.array([[1, 2], [3, 4 ]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.stack((arr1, arr2), axis=1)
print(arr, arr.shape)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]] (2, 2, 2)


In [81]:
arr = np.hstack((arr1, arr2))
print (arr, arr.shape)

[[1 2 5 6]
 [3 4 7 8]] (2, 4)


In [80]:
arr = np.vstack((arr1, arr2))
print (arr, arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


In [79]:
arr = np.dstack((arr1, arr2))
print (arr, arr.shape)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]] (2, 2, 2)


# **Splitting**

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newarr)

newarr = np.array_split(arr, 4)
print(newarr, type(newarr), type(newarr[0])) 

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])] <class 'list'> <class 'numpy.ndarray'>


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr) 

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr) 

# **Initialization**

In [ ]:
a=np.random.randint(100)
print (a)

a=np.random.rand()
print (a)

a=np.random.randint(low=0, high=100, size=(2,3))
print (a)

a=np.zeros((2,3)); print (a)
a=np.full((2,3), 5); print (a)
a=np.random.uniform(low=0, high=100, size=(2,3)); print (a)

# **Mulitplication**

In [70]:
a=3+8j
b=5-2j
print (np.dot(a, b), np.dot(6, 7))

(31+34j) 42


In [73]:
#dot

a=np.array([1,2,3])
print (a.shape, type(a))
b=np.full((3, ), 1)
print (b.shape, type(b))
d=np.dot(a, b)
print (a, b, d, d.shape, type(d))
#print (np.dot(2, a))

(3,) <class 'numpy.ndarray'>
(3,) <class 'numpy.ndarray'>
[1 2 3] [1 1 1] 6 () <class 'numpy.int64'>
[2 4 6]


###Q)Normalized Dot Product of two numpy 1-D arrays 

In [ ]:
a=np.full((2, 3, 4), 1)
b=np.random.uniform(low=2, high=3, size=(5, 4, 2)).astype(int)
print (a.shape)
print (b.shape)

d=np.dot(a, b)

In [69]:
#matmul: (n,k),(k,m)->(n,m).

a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])
e = np.ones([1, 4])
print (a.shape, c.shape, e.shape)
d=np.dot(a, c)
print (d.shape)
v=np.matmul(a, c)
print (v.shape)
#ae=a+e#np.matmul(a, e)
#print (ae.shape)

(9, 5, 7, 4) (9, 5, 4, 3) (1, 4)
(9, 5, 7, 9, 5, 3)
(9, 5, 7, 3)
(9, 5, 7, 4)


# **Broadcast operation**

In [ ]:
#A way of vectorizing matrix operation.
#matrices are treated as element and 

## Q)Broadcast matrix e over a for matrix multiplication

# **Tensorflow tf**

In [78]:
a = np.array([[1, 2, 3], [4, 5, 6]])
t=tf.constant(a)
print (t, type(t), t.shape)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64) <class 'tensorflow.python.framework.ops.EagerTensor'> (2, 3)


For a functional keras model: if it has 2 input nodes and 2 output nodes. Then model will accept inputs as:
X= [  (#samples, each_instance_shape),  (#samples, each_instance_shape) ]
ouputs:
Y= [  (#samples, output_instance_shape),  (#samples, each_instance_shape) ]